package com.learneveryday.app

object LearningCurriculum {
    
    fun getAllTopics(): List<LearningTopic> {
        return listOf(
            getPythonCurriculum(),
            getJavaScriptCurriculum(),
            getKotlinCurriculum(),
            getJavaCurriculum(),
            getWebDevCurriculum(),
            getDataScienceCurriculum()
        )
    }
    
    private fun getPythonCurriculum() = LearningTopic(
        id = "python",
        title = "Python Programming",
        description = "Learn Python from basics to advanced concepts",
        lessons = listOf(
            Lesson(1, "Introduction to Python", "Python is a high-level, interpreted programming language known for its simplicity and readability. It was created by Guido van Rossum and first released in 1991.\n\nKey features:\n• Easy to learn and read\n• Versatile and powerful\n• Large standard library\n• Great community support\n\nPython is used for web development, data science, AI, automation, and more!"),
            Lesson(2, "Installing Python", "To start coding in Python, you need to install it on your computer.\n\nSteps:\n1. Visit python.org\n2. Download the latest version (3.11+)\n3. Run the installer\n4. Check 'Add Python to PATH'\n5. Verify installation by typing 'python --version' in terminal\n\nYou can also use online editors like repl.it or Google Colab to practice without installation."),
            Lesson(3, "Your First Program", "Let's write your first Python program!\n\nprint(\"Hello, World!\")\n\nThis simple line outputs text to the screen. The print() function displays whatever you put inside the parentheses.\n\nTry it:\n• Open Python IDLE or a text editor\n• Type: print(\"Hello, World!\")\n• Save as hello.py\n• Run it!\n\nCongratulations! You're now a Python programmer!"),
            Lesson(4, "Variables and Data Types", "Variables store data in your programs.\n\nBasic syntax:\nname = \"John\"  # String\nage = 25       # Integer\nheight = 5.9   # Float\nis_student = True  # Boolean\n\nPython automatically detects the data type. You don't need to declare it explicitly!\n\nNaming rules:\n• Start with letter or underscore\n• No spaces (use underscore)\n• Case sensitive\n• Avoid Python keywords"),
            Lesson(5, "Basic Operators", "Operators perform operations on variables and values.\n\nArithmetic:\n+ (add), - (subtract), * (multiply), / (divide), % (modulo), ** (power)\n\nComparison:\n== (equal), != (not equal), > (greater), < (less), >= (greater or equal), <= (less or equal)\n\nLogical:\nand, or, not\n\nExample:\nx = 10\ny = 3\nprint(x + y)  # 13\nprint(x > y)  # True"),
            Lesson(6, "Strings and String Methods", "Strings are sequences of characters enclosed in quotes.\n\nCreating strings:\nname = \"Alice\"\ngreeting = 'Hello'\nmultiline = \"\"\"This is\na multiline\nstring\"\"\"\n\nUseful methods:\n• upper() - convert to uppercase\n• lower() - convert to lowercase\n• strip() - remove whitespace\n• split() - split into list\n• replace() - replace characters\n• len() - get length"),
            Lesson(7, "Lists", "Lists store multiple items in a single variable.\n\nCreating lists:\nfruits = [\"apple\", \"banana\", \"cherry\"]\nnumbers = [1, 2, 3, 4, 5]\nmixed = [1, \"hello\", True, 3.14]\n\nAccessing items:\nprint(fruits[0])  # \"apple\"\nprint(fruits[-1])  # \"cherry\" (last item)\n\nCommon operations:\n• append() - add item\n• remove() - remove item\n• len() - get length\n• sort() - sort list"),
            Lesson(8, "Dictionaries", "Dictionaries store data in key-value pairs.\n\nCreating dictionaries:\nperson = {\n    \"name\": \"John\",\n    \"age\": 30,\n    \"city\": \"New York\"\n}\n\nAccessing values:\nprint(person[\"name\"])  # \"John\"\nprint(person.get(\"age\"))  # 30\n\nAdding/modifying:\nperson[\"email\"] = \"john@example.com\"\nperson[\"age\"] = 31\n\nDictionaries are perfect for structured data!"),
            Lesson(9, "If Statements", "If statements allow conditional execution of code.\n\nBasic syntax:\nage = 18\nif age >= 18:\n    print(\"Adult\")\nelif age >= 13:\n    print(\"Teenager\")\nelse:\n    print(\"Child\")\n\nNote the indentation! Python uses indentation to define code blocks.\n\nYou can combine conditions:\nif age >= 18 and age < 65:\n    print(\"Working age\")"),
            Lesson(10, "For Loops", "For loops iterate over sequences.\n\nIterating over lists:\nfruits = [\"apple\", \"banana\", \"cherry\"]\nfor fruit in fruits:\n    print(fruit)\n\nUsing range():\nfor i in range(5):  # 0 to 4\n    print(i)\n\nfor i in range(1, 11):  # 1 to 10\n    print(i)\n\nLoops are essential for repetitive tasks!"),
            Lesson(11, "While Loops", "While loops execute code while a condition is true.\n\nBasic syntax:\ncount = 0\nwhile count < 5:\n    print(count)\n    count += 1\n\nBe careful with infinite loops!\n\nUsing break and continue:\nwhile True:\n    user_input = input(\"Enter 'quit' to exit: \")\n    if user_input == 'quit':\n        break\n    print(f\"You entered: {user_input}\")"),
            Lesson(12, "Functions", "Functions are reusable blocks of code.\n\nDefining functions:\ndef greet(name):\n    return f\"Hello, {name}!\"\n\nresult = greet(\"Alice\")\nprint(result)  # \"Hello, Alice!\"\n\nFunctions with multiple parameters:\ndef add(a, b):\n    return a + b\n\ntotal = add(5, 3)\nprint(total)  # 8\n\nDefault parameters:\ndef greet(name=\"Guest\"):\n    return f\"Hello, {name}!\""),
            Lesson(13, "List Comprehensions", "List comprehensions create lists in a concise way.\n\nBasic syntax:\nsquares = [x**2 for x in range(10)]\nprint(squares)  # [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]\n\nWith conditions:\nevens = [x for x in range(20) if x % 2 == 0]\n\nTransforming lists:\nnames = [\"alice\", \"bob\", \"charlie\"]\nupper_names = [name.upper() for name in names]\n\nThis is more Pythonic than traditional loops!"),
            Lesson(14, "File Handling", "Python makes it easy to work with files.\n\nReading files:\nwith open('file.txt', 'r') as file:\n    content = file.read()\n    print(content)\n\nWriting files:\nwith open('output.txt', 'w') as file:\n    file.write('Hello, World!')\n\nAppending to files:\nwith open('log.txt', 'a') as file:\n    file.write('New entry\\n')\n\nThe 'with' statement automatically closes files!"),
            Lesson(15, "Exception Handling", "Handle errors gracefully with try-except blocks.\n\nBasic syntax:\ntry:\n    result = 10 / 0\nexcept ZeroDivisionError:\n    print(\"Cannot divide by zero!\")\n\nMultiple exceptions:\ntry:\n    value = int(input(\"Enter a number: \"))\n    result = 10 / value\nexcept ValueError:\n    print(\"Invalid input!\")\nexcept ZeroDivisionError:\n    print(\"Cannot divide by zero!\")\nfinally:\n    print(\"Cleanup code here\")"),
            Lesson(16, "Classes and Objects", "Object-oriented programming with classes.\n\nDefining a class:\nclass Dog:\n    def __init__(self, name, age):\n        self.name = name\n        self.age = age\n    \n    def bark(self):\n        return f\"{self.name} says Woof!\"\n\nCreating objects:\nmy_dog = Dog(\"Buddy\", 3)\nprint(my_dog.bark())  # \"Buddy says Woof!\"\nprint(my_dog.age)  # 3\n\nClasses help organize related data and functions!"),
            Lesson(17, "Modules and Imports", "Organize code across multiple files using modules.\n\nImporting modules:\nimport math\nprint(math.pi)  # 3.141592653589793\n\nImporting specific functions:\nfrom math import sqrt, pow\nprint(sqrt(16))  # 4.0\n\nCreating your own modules:\n# In mymodule.py\ndef greet(name):\n    return f\"Hello, {name}!\"\n\n# In main.py\nimport mymodule\nprint(mymodule.greet(\"Alice\"))"),
            Lesson(18, "Lambda Functions", "Lambda functions are small anonymous functions.\n\nBasic syntax:\nsquare = lambda x: x**2\nprint(square(5))  # 25\n\nWith multiple parameters:\nadd = lambda a, b: a + b\nprint(add(3, 4))  # 7\n\nUseful with map, filter:\nnumbers = [1, 2, 3, 4, 5]\nsquared = list(map(lambda x: x**2, numbers))\nprint(squared)  # [1, 4, 9, 16, 25]\n\nGreat for simple, one-line functions!"),
            Lesson(19, "Working with JSON", "JSON is a popular data format for APIs and config files.\n\nimport json\n\n# Python dict to JSON:\ndata = {\"name\": \"Alice\", \"age\": 30}\njson_string = json.dumps(data)\nprint(json_string)\n\n# JSON to Python dict:\njson_data = '{\"name\": \"Bob\", \"age\": 25}'\nobj = json.loads(json_data)\nprint(obj[\"name\"])  # \"Bob\"\n\n# Reading/writing JSON files:\nwith open('data.json', 'w') as f:\n    json.dump(data, f)"),
            Lesson(20, "Virtual Environments", "Virtual environments isolate project dependencies.\n\nCreating a virtual environment:\npython -m venv myenv\n\nActivating:\n# Windows:\nmyenv\\Scripts\\activate\n\n# Mac/Linux:\nsource myenv/bin/activate\n\nInstalling packages:\npip install requests\n\nSaving dependencies:\npip freeze > requirements.txt\n\nInstalling from requirements:\npip install -r requirements.txt\n\nAlways use virtual environments for projects!"),
            Lesson(21, "Working with APIs", "APIs let you interact with web services.\n\nimport requests\n\n# GET request:\nresponse = requests.get('https://api.example.com/data')\nif response.status_code == 200:\n    data = response.json()\n    print(data)\n\n# POST request:\npayload = {'key': 'value'}\nresponse = requests.post('https://api.example.com/submit', json=payload)\n\n# Headers:\nheaders = {'Authorization': 'Bearer token'}\nresponse = requests.get('https://api.example.com/data', headers=headers)"),
            Lesson(22, "Regular Expressions", "Regex patterns match and manipulate text.\n\nimport re\n\n# Finding patterns:\ntext = \"My email is john@example.com\"\npattern = r'\\w+@\\w+\\.\\w+'\nmatch = re.search(pattern, text)\nif match:\n    print(match.group())  # \"john@example.com\"\n\n# Finding all matches:\nphones = re.findall(r'\\d{3}-\\d{4}', text)\n\n# Replacing:\nnew_text = re.sub(r'\\d+', 'X', text)\n\nRegex is powerful for text processing!"),
            Lesson(23, "Testing with unittest", "Write tests to ensure code works correctly.\n\nimport unittest\n\ndef add(a, b):\n    return a + b\n\nclass TestMath(unittest.TestCase):\n    def test_add(self):\n        self.assertEqual(add(2, 3), 5)\n        self.assertEqual(add(-1, 1), 0)\n    \n    def test_add_strings(self):\n        self.assertEqual(add('a', 'b'), 'ab')\n\nif __name__ == '__main__':\n    unittest.main()\n\nTesting catches bugs early!"),
            Lesson(24, "Best Practices & Next Steps", "Python best practices and where to go next.\n\nBest Practices:\n• Follow PEP 8 style guide\n• Write docstrings for functions\n• Use meaningful variable names\n• Keep functions small and focused\n• Handle exceptions properly\n• Write tests for your code\n\nNext Steps:\n• Build projects (web apps, automation scripts)\n• Learn frameworks (Django, Flask, FastAPI)\n• Explore data science (pandas, numpy)\n• Contribute to open source\n• Never stop learning!\n\nCongratulations on completing Python basics!")
        )
    )
    
    private fun getJavaScriptCurriculum() = LearningTopic(
        id = "javascript",
        title = "JavaScript",
        description = "Master JavaScript for web development",
        lessons = listOf(
            Lesson(1, "Introduction to JavaScript", "JavaScript is the programming language of the web. It runs in browsers and allows you to create interactive websites.\n\nKey features:\n• Client-side scripting\n• Dynamic and versatile\n• Event-driven programming\n• Runs in all modern browsers\n\nJavaScript powers modern web applications from simple interactions to complex single-page apps."),
            Lesson(2, "JavaScript Basics", "Getting started with JavaScript syntax.\n\nVariables:\nlet name = 'John';\nconst age = 30;\nvar oldWay = 'avoid var';\n\nData types:\n• String: 'hello'\n• Number: 42\n• Boolean: true/false\n• Object: {key: 'value'}\n• Array: [1, 2, 3]\n• null and undefined\n\nJavaScript is loosely typed - types are determined automatically."),
            Lesson(3, "Functions", "Functions are reusable blocks of code.\n\nFunction declaration:\nfunction greet(name) {\n    return `Hello, ${name}!`;\n}\n\nArrow functions:\nconst add = (a, b) => a + b;\n\nCallback functions:\nsetTimeout(() => {\n    console.log('Delayed message');\n}, 1000);\n\nFunctions are first-class objects in JavaScript!"),
            Lesson(4, "DOM Manipulation", "The DOM (Document Object Model) represents HTML.\n\nSelecting elements:\nconst element = document.getElementById('myId');\nconst elements = document.querySelectorAll('.myClass');\n\nModifying content:\nelement.textContent = 'New text';\nelement.innerHTML = '<strong>Bold text</strong>';\n\nChanging styles:\nelement.style.color = 'red';\nelement.classList.add('active');\n\nDOM manipulation makes pages interactive!"),
            Lesson(5, "Events", "Events respond to user interactions.\n\nAdding event listeners:\nbutton.addEventListener('click', function() {\n    console.log('Button clicked!');\n});\n\nCommon events:\n• click - mouse click\n• submit - form submission\n• keypress - keyboard press\n• load - page loaded\n• change - input changed\n\nEvent object:\nelement.addEventListener('click', (e) => {\n    console.log(e.target);\n});"),
            Lesson(6, "Arrays and Array Methods", "Arrays store ordered collections.\n\nCreating arrays:\nconst fruits = ['apple', 'banana', 'cherry'];\n\nUseful methods:\n• push() - add to end\n• pop() - remove from end\n• map() - transform each element\n• filter() - filter elements\n• reduce() - reduce to single value\n• forEach() - iterate over elements\n\nExample:\nconst numbers = [1, 2, 3, 4];\nconst doubled = numbers.map(n => n * 2);"),
            Lesson(7, "Objects", "Objects store key-value pairs.\n\nCreating objects:\nconst person = {\n    name: 'Alice',\n    age: 30,\n    greet() {\n        return `Hi, I'm ${this.name}`;\n    }\n};\n\nAccessing properties:\nconsole.log(person.name);\nconsole.log(person['age']);\n\nAdding properties:\nperson.email = 'alice@example.com';\n\nObjects are fundamental in JavaScript!"),
            Lesson(8, "Promises and Async/Await", "Handle asynchronous operations.\n\nPromises:\nfetch('https://api.example.com/data')\n    .then(response => response.json())\n    .then(data => console.log(data))\n    .catch(error => console.error(error));\n\nAsync/await:\nasync function getData() {\n    try {\n        const response = await fetch('url');\n        const data = await response.json();\n        return data;\n    } catch (error) {\n        console.error(error);\n    }\n}\n\nAsync/await makes async code easier to read!"),
            Lesson(9, "ES6+ Features", "Modern JavaScript features.\n\nDestructuring:\nconst {name, age} = person;\nconst [first, second] = array;\n\nSpread operator:\nconst newArray = [...oldArray, 4, 5];\nconst newObj = {...oldObj, key: 'value'};\n\nTemplate literals:\nconst message = `Hello, ${name}!`;\n\nDefault parameters:\nfunction greet(name = 'Guest') {\n    return `Hello, ${name}!`;\n}\n\nThese features make code cleaner!"),
            Lesson(10, "Error Handling", "Handle errors gracefully.\n\nTry-catch:\ntry {\n    const result = riskyOperation();\n} catch (error) {\n    console.error('Error:', error.message);\n} finally {\n    console.log('Cleanup');\n}\n\nThrowing errors:\nfunction divide(a, b) {\n    if (b === 0) {\n        throw new Error('Division by zero');\n    }\n    return a / b;\n}\n\nPromise error handling:\npromise.catch(error => console.error(error));"),
            Lesson(11, "Classes", "Object-oriented programming with classes.\n\nDefining classes:\nclass Animal {\n    constructor(name) {\n        this.name = name;\n    }\n    \n    speak() {\n        return `${this.name} makes a sound`;\n    }\n}\n\nInheritance:\nclass Dog extends Animal {\n    speak() {\n        return `${this.name} barks`;\n    }\n}\n\nconst dog = new Dog('Buddy');\nconsole.log(dog.speak());"),
            Lesson(12, "Modules", "Organize code with modules.\n\nExporting:\n// math.js\nexport const add = (a, b) => a + b;\nexport const subtract = (a, b) => a - b;\n\nImporting:\nimport { add, subtract } from './math.js';\n\nDefault exports:\n// utils.js\nexport default function() { }\n\n// main.js\nimport utils from './utils.js';\n\nModules help organize large applications!"),
            Lesson(13, "Local Storage", "Store data in the browser.\n\nSaving data:\nlocalStorage.setItem('username', 'Alice');\nlocalStorage.setItem('settings', JSON.stringify(settings));\n\nRetrieving data:\nconst username = localStorage.getItem('username');\nconst settings = JSON.parse(localStorage.getItem('settings'));\n\nRemoving data:\nlocalStorage.removeItem('username');\nlocalStorage.clear(); // Remove all\n\nPerfect for user preferences!"),
            Lesson(14, "Fetch API", "Make HTTP requests.\n\nGET request:\nfetch('https://api.example.com/data')\n    .then(response => response.json())\n    .then(data => console.log(data));\n\nPOST request:\nfetch('https://api.example.com/submit', {\n    method: 'POST',\n    headers: {\n        'Content-Type': 'application/json'\n    },\n    body: JSON.stringify({key: 'value'})\n})\n.then(response => response.json())\n.then(data => console.log(data));"),
            Lesson(15, "JSON", "Work with JSON data.\n\nJSON is JavaScript Object Notation.\n\nParsing JSON:\nconst jsonString = '{\"name\": \"Alice\", \"age\": 30}';\nconst obj = JSON.parse(jsonString);\n\nStringifying objects:\nconst obj = {name: 'Bob', age: 25};\nconst jsonString = JSON.stringify(obj);\n\nPretty printing:\nconst pretty = JSON.stringify(obj, null, 2);\n\nJSON is the standard for data exchange!"),
            Lesson(16, "Closures", "Functions that remember their environment.\n\nExample:\nfunction counter() {\n    let count = 0;\n    return function() {\n        count++;\n        return count;\n    };\n}\n\nconst increment = counter();\nconsole.log(increment()); // 1\nconsole.log(increment()); // 2\n\nClosures enable:\n• Data privacy\n• Function factories\n• Callbacks with state\n\nA powerful JavaScript feature!"),
            Lesson(17, "Array Destructuring", "Extract values from arrays easily.\n\nBasic destructuring:\nconst [first, second, third] = [1, 2, 3];\n\nSkipping elements:\nconst [first, , third] = [1, 2, 3];\n\nRest operator:\nconst [first, ...rest] = [1, 2, 3, 4];\nconsole.log(rest); // [2, 3, 4]\n\nSwapping variables:\nlet a = 1, b = 2;\n[a, b] = [b, a];\n\nDestructuring makes code cleaner!"),
            Lesson(18, "Object Destructuring", "Extract object properties easily.\n\nBasic destructuring:\nconst {name, age} = person;\n\nRenaming:\nconst {name: fullName, age: years} = person;\n\nDefault values:\nconst {name = 'Guest', age = 0} = person;\n\nNested destructuring:\nconst {address: {city}} = person;\n\nFunction parameters:\nfunction greet({name, age}) {\n    console.log(`${name} is ${age}`);\n}\n\nVery useful with APIs!"),
            Lesson(19, "Map and Set", "Special collection types.\n\nMap:\nconst map = new Map();\nmap.set('key', 'value');\nconst value = map.get('key');\nmap.has('key'); // true\nmap.delete('key');\n\nSet:\nconst set = new Set([1, 2, 3, 3]);\nset.add(4);\nset.has(2); // true\nset.delete(1);\nset.size; // 3\n\nMaps allow any key type, Sets store unique values!"),
            Lesson(20, "Regular Expressions", "Pattern matching with regex.\n\nCreating regex:\nconst pattern = /hello/i; // case insensitive\nconst pattern2 = new RegExp('hello', 'i');\n\nTesting:\npattern.test('Hello'); // true\n\nMatching:\nconst matches = 'hello world'.match(/\\w+/g);\n\nReplacing:\nconst newStr = 'hello'.replace(/l/g, 'L');\n\nCommon patterns:\n• \\d - digit\n• \\w - word character\n• . - any character\n• + - one or more"),
            Lesson(21, "Timers", "Schedule code execution.\n\nsetTimeout:\nsetTimeout(() => {\n    console.log('Delayed');\n}, 1000); // 1 second\n\nsetInterval:\nconst intervalId = setInterval(() => {\n    console.log('Repeating');\n}, 1000);\n\nClearing timers:\nclearTimeout(timeoutId);\nclearInterval(intervalId);\n\nDebouncing:\nlet timeoutId;\nfunction debounce(fn, delay) {\n    clearTimeout(timeoutId);\n    timeoutId = setTimeout(fn, delay);\n}"),
            Lesson(22, "Event Loop", "Understanding JavaScript's concurrency model.\n\nJavaScript is single-threaded but non-blocking.\n\nCall stack:\n• Executes synchronous code\n• One function at a time\n\nCallback queue:\n• Holds callback functions\n• Executed after call stack is empty\n\nEvent loop:\n• Monitors call stack and queue\n• Moves callbacks to stack when empty\n\nThis enables async operations without multiple threads!"),
            Lesson(23, "Best Practices", "Write better JavaScript code.\n\nCode style:\n• Use const/let, not var\n• Use === instead of ==\n• Use arrow functions appropriately\n• Avoid global variables\n\nPerformance:\n• Minimize DOM manipulation\n• Use event delegation\n• Avoid memory leaks\n\nSecurity:\n• Validate user input\n• Avoid eval()\n• Use HTTPS for API calls\n\nFollow these for cleaner, safer code!"),
            Lesson(24, "Next Steps", "Continue your JavaScript journey.\n\nFrameworks to learn:\n• React - UI library\n• Vue - Progressive framework\n• Angular - Full framework\n• Node.js - Server-side JavaScript\n\nTools to explore:\n• npm - Package manager\n• Webpack - Module bundler\n• Babel - JS compiler\n• ESLint - Code linter\n\nProjects to build:\n• Todo app\n• Weather app\n• Chat application\n\nKeep coding and building!")
        )
    )
    
    private fun getKotlinCurriculum() = LearningTopic(
        id = "kotlin",
        title = "Kotlin for Android",
        description = "Learn Kotlin programming for Android development",
        lessons = listOf(
            Lesson(1, "Introduction to Kotlin", "Kotlin is a modern programming language that runs on the JVM and is officially supported for Android development.\n\nKey features:\n• Concise syntax\n• Null safety\n• Interoperable with Java\n• Coroutines for async programming\n\nGoogle announced Kotlin as preferred for Android in 2019!"),
            Lesson(2, "Variables and Types", "Declare variables with val and var.\n\nval name = \"John\"  // Immutable\nvar age = 25       // Mutable\n\nExplicit types:\nval name: String = \"John\"\nval age: Int = 25\n\nCommon types:\n• Int, Long, Double, Float\n• String, Char, Boolean\n• Any (like Object in Java)\n\nPrefer val over var for immutability!"),
            Lesson(3, "Functions", "Functions in Kotlin are declared with fun.\n\nBasic function:\nfun greet(name: String): String {\n    return \"Hello, $name!\"\n}\n\nSingle expression:\nfun add(a: Int, b: Int) = a + b\n\nDefault parameters:\nfun greet(name: String = \"Guest\") = \"Hello, $name!\"\n\nNamed arguments:\ngreet(name = \"Alice\")"),
            Lesson(4, "Null Safety", "Kotlin eliminates null pointer exceptions.\n\nNullable types:\nvar name: String? = null\n\nSafe call:\nval length = name?.length\n\nElvis operator:\nval length = name?.length ?: 0\n\nNot-null assertion:\nval length = name!!.length // Throws if null\n\nNull safety is a killer feature!"),
            Lesson(5, "Classes and Objects", "Object-oriented programming in Kotlin.\n\nSimple class:\nclass Person(val name: String, var age: Int)\n\nCreating objects:\nval person = Person(\"Alice\", 30)\n\nData classes:\ndata class User(val id: Int, val name: String)\n\nData classes provide:\n• equals() and hashCode()\n• toString()\n• copy()"),
            Lesson(6, "Conditionals", "If, when, and other conditionals.\n\nIf expression:\nval max = if (a > b) a else b\n\nWhen expression:\nwhen (x) {\n    1 -> print(\"One\")\n    2, 3 -> print(\"Two or Three\")\n    in 4..10 -> print(\"Between 4 and 10\")\n    else -> print(\"Other\")\n}\n\nWhen replaces switch in Kotlin!"),
            Lesson(7, "Collections", "Lists, sets, and maps in Kotlin.\n\nList:\nval list = listOf(1, 2, 3)  // Immutable\nval mutable = mutableListOf(1, 2, 3)\n\nSet:\nval set = setOf(1, 2, 3)\n\nMap:\nval map = mapOf(\"key\" to \"value\")\n\nFiltering:\nval evens = list.filter { it % 2 == 0 }\n\nMapping:\nval doubled = list.map { it * 2 }"),
            Lesson(8, "Lambdas", "Lambda expressions and higher-order functions.\n\nBasic lambda:\nval sum = { a: Int, b: Int -> a + b }\n\nWith collections:\nlist.forEach { println(it) }\n\nIt keyword:\nlist.filter { it > 5 }\n\nHigher-order function:\nfun operate(a: Int, b: Int, op: (Int, Int) -> Int) = op(a, b)\n\nLambdas make code concise!"),
            Lesson(9, "Extension Functions", "Add functions to existing classes.\n\nDefining extensions:\nfun String.addExclamation() = \"$this!\"\n\nUsing:\nval result = \"Hello\".addExclamation() // \"Hello!\"\n\nWith parameters:\nfun Int.times(str: String) = str.repeat(this)\n\n3.times(\"Ha\") // \"HaHaHa\"\n\nExtensions don't modify original classes!"),
            Lesson(10, "Object and Companion", "Singletons and static members.\n\nObject declaration:\nobject Database {\n    fun connect() { }\n}\n\nCompanion object:\nclass MyClass {\n    companion object {\n        const val TAG = \"MyClass\"\n        fun create() = MyClass()\n    }\n}\n\nUsing:\nMyClass.TAG\nMyClass.create()"),
            Lesson(11, "Sealed Classes", "Restricted class hierarchies.\n\nSealed class:\nsealed class Result {\n    data class Success(val data: String) : Result()\n    data class Error(val message: String) : Result()\n    object Loading : Result()\n}\n\nUsing with when:\nwhen (result) {\n    is Result.Success -> println(result.data)\n    is Result.Error -> println(result.message)\n    Result.Loading -> println(\"Loading...\")\n}\n\nGreat for state management!"),
            Lesson(12, "Coroutines Basics", "Asynchronous programming with coroutines.\n\nLaunching coroutine:\nGlobalScope.launch {\n    delay(1000)\n    println(\"World!\")\n}\n\nSuspend functions:\nsuspend fun fetchData(): String {\n    delay(1000)\n    return \"Data\"\n}\n\nAsync/await:\nval deferred = async { fetchData() }\nval result = deferred.await()\n\nCoroutines are lightweight threads!"),
            Lesson(13, "Android Activity", "Creating Android activities in Kotlin.\n\nBasic activity:\nclass MainActivity : AppCompatActivity() {\n    override fun onCreate(savedInstanceState: Bundle?) {\n        super.onCreate(savedInstanceState)\n        setContentView(R.layout.activity_main)\n    }\n}\n\nView binding:\nprivate lateinit var binding: ActivityMainBinding\n\nbinding = ActivityMainBinding.inflate(layoutInflater)\nsetContentView(binding.root)"),
            Lesson(14, "Android Views", "Working with UI components.\n\nFinding views:\nval button = findViewById<Button>(R.id.myButton)\n\nWith view binding:\nbinding.myButton.text = \"Click me\"\n\nClick listener:\nbinding.myButton.setOnClickListener {\n    // Handle click\n}\n\nView binding is the modern way!"),
            Lesson(15, "Intents", "Navigate between activities.\n\nExplicit intent:\nval intent = Intent(this, SecondActivity::class.java)\nstartActivity(intent)\n\nPassing data:\nintent.putExtra(\"key\", \"value\")\n\nReceiving data:\nval data = intent.getStringExtra(\"key\")\n\nImplicit intent:\nval intent = Intent(Intent.ACTION_VIEW, Uri.parse(\"https://google.com\"))\nstartActivity(intent)"),
            Lesson(16, "RecyclerView", "Display lists efficiently.\n\nAdapter:\nclass MyAdapter(private val items: List<String>) :\n    RecyclerView.Adapter<MyAdapter.ViewHolder>() {\n    \n    class ViewHolder(view: View) : RecyclerView.ViewHolder(view)\n    \n    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ViewHolder { }\n    \n    override fun onBindViewHolder(holder: ViewHolder, position: Int) { }\n    \n    override fun getItemCount() = items.size\n}"),
            Lesson(17, "ViewModel", "Manage UI-related data.\n\nCreating ViewModel:\nclass MyViewModel : ViewModel() {\n    private val _data = MutableLiveData<String>()\n    val data: LiveData<String> = _data\n    \n    fun updateData(newData: String) {\n        _data.value = newData\n    }\n}\n\nIn Activity:\nval viewModel: MyViewModel by viewModels()\nviewModel.data.observe(this) { data ->\n    // Update UI\n}"),
            Lesson(18, "LiveData", "Observable data holder.\n\nCreating LiveData:\nval data = MutableLiveData<String>()\n\nUpdating:\ndata.value = \"New value\"\n\nObserving:\ndata.observe(this) { value ->\n    textView.text = value\n}\n\nLiveData is lifecycle-aware!"),
            Lesson(19, "Room Database", "Local database for Android.\n\nEntity:\n@Entity\ndata class User(\n    @PrimaryKey val id: Int,\n    val name: String\n)\n\nDAO:\n@Dao\ninterface UserDao {\n    @Query(\"SELECT * FROM user\")\n    fun getAll(): List<User>\n    \n    @Insert\n    fun insert(user: User)\n}"),
            Lesson(20, "Retrofit", "HTTP client for Android.\n\nService interface:\ninterface ApiService {\n    @GET(\"users\")\n    suspend fun getUsers(): List<User>\n    \n    @POST(\"users\")\n    suspend fun createUser(@Body user: User): User\n}\n\nCreating client:\nval retrofit = Retrofit.Builder()\n    .baseUrl(\"https://api.example.com/\")\n    .addConverterFactory(GsonConverterFactory.create())\n    .build()"),
            Lesson(21, "Permissions", "Request runtime permissions.\n\nDeclare in manifest:\n<uses-permission android:name=\"android.permission.CAMERA\" />\n\nRequest at runtime:\nif (ContextCompat.checkSelfPermission(this, Manifest.permission.CAMERA)\n    != PackageManager.PERMISSION_GRANTED) {\n    ActivityCompat.requestPermissions(this,\n        arrayOf(Manifest.permission.CAMERA), REQUEST_CODE)\n}\n\nHandle result:\nonRequestPermissionsResult()"),
            Lesson(22, "Notifications", "Send notifications to users.\n\nCreate notification:\nval notification = NotificationCompat.Builder(this, CHANNEL_ID)\n    .setSmallIcon(R.drawable.ic_notification)\n    .setContentTitle(\"Title\")\n    .setContentText(\"Content\")\n    .setPriority(NotificationCompat.PRIORITY_HIGH)\n    .build()\n\nShow:\nNotificationManagerCompat.from(this)\n    .notify(notificationId, notification)"),
            Lesson(23, "Best Practices", "Android development best practices.\n\nArchitecture:\n• Use MVVM pattern\n• Separate concerns\n• Repository pattern\n\nPerformance:\n• Avoid memory leaks\n• Use appropriate data structures\n• Optimize RecyclerView\n\nTesting:\n• Write unit tests\n• Use dependency injection\n• Test ViewModels\n\nFollow Android guidelines!"),
            Lesson(24, "Next Steps", "Continue your Android journey.\n\nAdvanced topics:\n• Jetpack Compose\n• Dependency Injection (Hilt)\n• Navigation Component\n• WorkManager\n\nBuild projects:\n• Todo app\n• Note-taking app\n• Weather app\n• Social media app\n\nPublish to Play Store!\n\nCongratulations on completing Kotlin for Android!")
        )
    )
    
    // Simplified implementations for other topics
    private fun getJavaCurriculum() = LearningTopic(
        id = "java",
        title = "Java Programming",
        description = "Learn Java from fundamentals to advanced",
        lessons = (1..24).map { i ->
            Lesson(i, "Java Lesson $i", "This is lesson $i content for Java programming. Java is a popular object-oriented programming language used for enterprise applications, Android development, and more.")
        }
    )
    
    private fun getWebDevCurriculum() = LearningTopic(
        id = "webdev",
        title = "Web Development",
        description = "HTML, CSS, and JavaScript for modern web",
        lessons = (1..24).map { i ->
            Lesson(i, "Web Dev Lesson $i", "This is lesson $i content for Web Development. Learn to build beautiful, responsive websites using HTML5, CSS3, and modern JavaScript.")
        }
    )
    
    private fun getDataScienceCurriculum() = LearningTopic(
        id = "datascience",
        title = "Data Science Basics",
        description = "Introduction to data science and analytics",
        lessons = (1..24).map { i ->
            Lesson(i, "Data Science Lesson $i", "This is lesson $i content for Data Science. Explore data analysis, visualization, statistics, and machine learning fundamentals.")
        }
    )
}
